### ISSUE TITLE
[Feature]: Add a workflow to check that a package down site can be built

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-ost/ghactions4r#120]
### Is your feature request related to a problem? Please describe.

I sometimes make changes to the code, like removing a function, and then forget that there may be changes needed to the package down site like removing the function from a list of grouped functions.

### Describe the solution you would like.

Is there a way to add a workflow that just checks if a package down site builds successfully? That way, the new workflow could be used in tests run when checking Pull Requests because we do not actually want the built site to be deployed.

### Describe alternatives you have considered

* Write a note to have users check the package down site manually if one exists
* Modify the current workflow that builds the site to see if it is being ran on a pull request and only check if it can build
* Modify the current workflow to accept an argument if you actually want the site to be built

### Additional context

See [this issue in FIMS](https://github.com/NOAA-FIMS/FIMS/issues/595), where I did not make the necessary changes to the package down site and @Bai-Li-NOAA caught my error when reviewing a pull request.

**Comment by k-doering-NOAA** [comment]
Thanks @kellijohnson-NOAA! I think this would be possible by using `pkgdown::build_site()` (as shown in the [pkgdown documentation](https://pkgdown.r-lib.org/#usage) in the github actions and then saving the output as an artifact.

Here is the start for the reusable workflow (not tested yet)

```yml
# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_call:

name: build-pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: build pkgdown
        run: |
          Rscript -e 'pkgdown::build_site()'
     
      #save pkgdown output
      - uses: actions/upload-artifact@v4
        with:
          name: pkgdown-site
          path: docs/
     

```
