### ISSUE TITLE
[Feature]: calculate code coverage with GitHub actions, post on prs, and create cov display badge

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#160]
### Is your feature request related to a problem? Please describe.

It would be good to have a GitHub action that calculates code coverage and could post on a pull request.

@sbreitbart-NOAA 

### Describe the solution you would like.

use github actions

### Describe alternatives you have considered

use sonar qube

**Comment by k-doering-NOAA** [comment]
@sbreitbart-NOAA you can try testing the code coverage calculations with one of your pkgs, if you would like! Right now, when it runs, you can see the code coverage printed in the github action output in the test coverage step:

![screenshot of github action run output](https://github.com/user-attachments/assets/f7ca7388-a1f9-46c6-a048-5d7b76dfed42)

Or you can download the report from the github action from the summary page (not sure if there is a better format, there may be):

![screenshot illustrating where to get the report](https://github.com/user-attachments/assets/9a2c0105-f1a2-4594-899e-ca758cc4ac3f)

I haven't yet added these features:
- Ability to pass coverage calculation to a badge
- Ability to comment with code coverage info on a PR.

To test, copy this yaml into the folder with github actions in your project in a branch and push the change - the workflow should run. (once this is in main of ghactions4r, we will want to replace the `@calc-covr-codecov` with `@main`: 
```
# call a workflow that runs covr::codecov() to calculate code coverage
name: call-calc-covr-no-push
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
# The default is to run the workflow on every push or pull request to every branch.
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/calc-covr-no-push.yml@calc-covr-codecov
```

Let me know if you have any questions!
