### ISSUE TITLE
call-doc-and-style-r PR generates after code PR

### ISSUE THREAD

**Issue by efletcherPIFSC** [nmfs-ost/ghactions4r#30]
@k-doering-NOAA 

Our ss3diags repo is using the default call-doc-and-style-r action. The doc and r code styler action does not integrate with the code pull request, a separate pull request is generated for call-doc-and-style-r.

```
# document and style using reusable workflow
# This workflow runs devtools::document and styler::style_active_package(), then opens a pull request to the branch
# That started the workflow with the changes
name: call-doc-and-style-r
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# workflow_dispatch requires pushing a button to run the workflow manually. uncomment the following line to add:
  #workflow_dispatch:
  # Runs the workflow on each push to the main or master branch:
  push:
    branches: [main, master]
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/doc-and-style-r.yml@main
```

Is there a setup were that the **Doc and R code styler** integrate with code puil requests (similar to R CMD CHECK)?
