### ISSUE TITLE
[Feature]: make build triggers more selective

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-ost/ghactions4r#74]
### Is your feature request related to a problem? Please describe.

I noticed the build trigger for doc and style from the template runs on push to main - it could be more selective, e.g., 

```yml
on:
  # workflow_dispatch:
  push:
    paths:
      - 'R/**'
      - 'tests/**'
      - 'vignettes/**'
    branches: [main]
```

### Describe the solution you would like.

look at the templates and modify them to be more selective

### Describe alternatives you have considered

leave as is, which are simpler and easier to understand.
